export interface PaymentRawRow {
  paymentid?: number;
  paymentId?: number;
  amount?: string | number | null;
  paymentTypeId?: number | null;
  paymentMethodId?: number | null;
  recordedByUserId?: number | null;
  installmentId?: number | null;
  collectornname?: string | null;
  collectorName?: string | null;
  collectorid?: number | null;
  collectorId?: number | null;
  collectordocument?: string | null;
  collectorDocument?: string | null;
  collectorphone?: string | null;
  collectorPhone?: string | null;
  collectorroute?: string | null;
  collectorRoute?: string | null;
  collectorrouteid?: number | null;
  collectorRouteId?: number | null;
  loanid?: number | null;
  loanId?: number | null;
  paymentdate?: string | Date | null;
  paymentDate?: string | Date | null;
  customerid?: number | null;
  customerId?: number | null;
  customername?: string | null;
  customerName?: string | null;
  customerdocument?: string | null;
  customerDocument?: string | null;
  zonecustomerid?: number | null;
  zoneCustomerId?: number | null;
  zonecustomername?: string | null;
  zoneCustomerName?: string | null;
  zonecustomercode?: string | null;
  zoneCustomerCode?: string | null;
  customerroute?: string | null;
  customerRoute?: string | null;
  duedate?: string | Date | null;
  dueDate?: string | Date | null;
  ispaid?: boolean | null;
  isPaid?: boolean | null;
  totalamount?: string | number | null;
  totalAmount?: string | number | null;
  paidamount?: string | number | null;
  paidAmount?: string | number | null;
  paidat?: string | Date | null;
  paidAt?: string | Date | null;
  statusid?: number | null;
  statusId?: number | null;
  installmentsequence?: number | null;
  installmentSequence?: number | null;
  // plus any other DB column aliases
  [key: string]: unknown;
}