export interface PaymentRawRow {
  paymentId: number;
  amount: string | number;
  paymentTypeId: number | null;
  paymentMethodId: number | null;
  recordedByUserId: number | null;
  installmentId: number | null;
  collectorName: string | null;
  collectorId: number | null;
  collectorDocument: string | null;
  collectorPhone: string | null;
  collectorRoute: string | null;
  collectorRouteId: number | null;
  loanId: number | null;
  paymentDate: string | Date | null;
  customerId: number | null;
  customerName: string | null;
  customerDocument: string | null;
  zoneCustomerId: number | null;
  zoneCustomerName: string | null;
  zoneCustomerCode: string | null;
  customerRoute: string | null;
  dueDate: string | Date | null;
  isPaid: boolean | null;
  totalAmount: string | number | null;
  paidAmount: string | number | null;
  paidAt: string | Date | null;
  statusId: number | null;
  installmentSequence: number | null;
}